/**
 * The compiled About page, and the small lookups it is read through.
 *
 * The help centre lives in `help-content.ts` rather than here, so that /about does not carry
 * thirty-three help articles it never renders.
 *
 * `content/about.json` is written by `scripts/site-content.ts` from `docs/copy/about.md` on every
 * build. It is checked in so a clone type-checks and tests without running the build first, and
 * regenerated by the build so it cannot drift from the copy a reviewer edits.
 */

import aboutJson from './content/about.json';
import type { AboutDoc, Block } from './markdown';
import { inlineText } from './markdown';

// The JSON is written by the compiler against this exact type; the assertion is where that contract
// is stated. `content.test.ts` checks the shipped file really does hold it.
export const ABOUT = aboutJson as unknown as AboutDoc;

/** The blocks of one labelled field of `about.md`, or null where the copy no longer has it. */
export function aboutField(heading: string, label: string): Block[] | null {
  const section = ABOUT.sections.find((s) => s.heading === heading);
  return section?.fields.find((f) => f.label === label)?.blocks ?? null;
}

/** One field as a plain string — for a heading, an eyebrow, a single line. Empty where absent. */
export function aboutLine(heading: string, label: string): string {
  const blocks = aboutField(heading, label);
  const first = blocks?.[0];
  return first && first.k !== 'rule' && first.k !== 'ul' && first.k !== 'ol'
    ? inlineText(first.text)
    : '';
}

/** Every field of a section whose label starts with `prefix` — the five promises, in order. */
export function aboutFields(heading: string, prefix: string): { label: string; blocks: Block[] }[] {
  const section = ABOUT.sections.find((s) => s.heading === heading);
  return section?.fields.filter((f) => f.label.startsWith(prefix)) ?? [];
}
