/**
 * The compiled help centre.
 *
 * It is a module of its own, and that is the whole point: thirty-three articles is about 30 kB
 * gzipped, and /about has no use for a single word of it. Kept in the shared `content.ts` it would
 * be hoisted into the chunk both pages load, and a visitor reading the About page on a 2G
 * connection would pay for the entire help centre to render a page that never mentions it.
 *
 * `content/help.json` is written by `scripts/site-content.ts` from `docs/copy/help-centre/**` on
 * every build. It is checked in so a clone type-checks and tests without running the build first,
 * and regenerated by the build so it cannot drift from the copy a reviewer edits.
 */

import helpJson from './content/help.json';
import type { HelpDoc } from './markdown';

// The JSON is written by the compiler against this exact type; the assertion is where that contract
// is stated. `content.test.ts` checks the shipped file really does hold it.
export const HELP = helpJson as unknown as HelpDoc;
