/**
 * The twelve golden boards, as the bench sees them.
 *
 * The JSON beside this file is generated by `build.ts` and is the single source of truth shared
 * with the brain's own golden test — the hand and the brain read the same bytes, so a board that
 * passes on one side cannot quietly differ on the other.
 */

import { parseBoardPlan } from '@wobo/wobo';
import benzene from './benzene.json';
import foodWeb from './food-web.json';
import incline from './free-body-incline.json';
import longDivision from './long-division.json';
import photosynthesis from './photosynthesis-balance.json';
import plantCell from './plant-cell.json';
import projectile from './projectile-apex.json';
import pythagoras from './pythagoras.json';
import circuit from './series-circuit.json';
import tangent from './tangent-parabola.json';
import timeline from './timeline.json';
import titration from './titration-curve.json';
import type { GoldenBoard } from './types';

export type { AnchorForm, GoldenBoard, GoldenExpectation, GoldenNumber } from './types';

const RAW = [
  pythagoras,
  tangent,
  longDivision,
  projectile,
  incline,
  circuit,
  benzene,
  photosynthesis,
  titration,
  plantCell,
  foodWeb,
  timeline,
] as unknown as GoldenBoard[];

/**
 * Every plan goes through the shipping parser on the way in, exactly as a streamed turn does. A
 * fixture that would be dropped on the wire is dropped here too, and the bench shows the shortfall
 * rather than a board that looks fine because the test data skipped the door.
 */
export const GOLDEN_BOARDS: GoldenBoard[] = RAW.map((board) => ({
  ...board,
  plan: parseBoardPlan(board.plan),
}));

export const GOLDEN_NAMES: string[] = GOLDEN_BOARDS.map((b) => b.name);

export function goldenBoard(name: string): GoldenBoard | undefined {
  return GOLDEN_BOARDS.find((b) => b.name === name);
}
