/**
 * The generated board list, checked against the registry it claims to come from.
 *
 * `boards.json` is a build artefact of `scripts/landing-boards.ts`, and this is the test that keeps
 * it honest: every id must still exist in `content/curriculum/frameworks.seed.json`, every long
 * name must be the registry's, every chip label must be a name that framework actually answers to,
 * and the totals under the chips must be the registry's own counts. If the content workflow renames
 * or drops a framework, this fails rather than the page quietly lying.
 *
 * The content directory is read, never written.
 */

import { describe, expect, it } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildLandingBoards, CURATED, chipLabel, type Seed } from '../../../scripts/landing-boards';
import boards from './boards.json';
import { countLine } from './sections/Boards';

const SEED = join(
  import.meta.dir,
  '..',
  '..',
  '..',
  '..',
  '..',
  'content',
  'curriculum',
  'frameworks.seed.json',
);
const seed = JSON.parse(readFileSync(SEED, 'utf8')) as Seed;
const byId = new Map(seed.frameworks.map((f) => [f.id, f]));

describe('boards.json', () => {
  it('shows enough boards to be a claim and few enough to be a page', () => {
    expect(boards.shown.length).toBeGreaterThanOrEqual(12);
    expect(boards.shown.length).toBeLessThanOrEqual(24);
  });

  it('names no board twice', () => {
    const ids = boards.shown.map((b) => b.id);
    expect(new Set(ids).size).toBe(ids.length);
    const shorts = boards.shown.map((b) => b.short);
    expect(new Set(shorts).size).toBe(shorts.length);
  });

  it('carries only frameworks that are still in the registry', () => {
    for (const board of boards.shown) expect(byId.has(board.id)).toBe(true);
  });

  it('uses the registry’s own long name', () => {
    for (const board of boards.shown) expect(board.name).toBe(byId.get(board.id)?.name ?? '');
  });

  it('uses a short name the framework actually answers to', () => {
    // The chip's WORDS are the registry's; only its CASE is ours (`chipLabel`), so the comparison
    // is made through the same normalisation rather than being loosened.
    for (const board of boards.shown) {
      const f = byId.get(board.id);
      const names = [f?.name ?? '', ...(f?.aliases ?? [])];
      const known = names.some((n) => chipLabel(n) === board.short);
      expect(known).toBe(true);
    }
  });

  it('writes every chip in the page’s own sentence case', () => {
    // Side by side, "Australian Curriculum" beside "Ontario curriculum" reads as a typo. The
    // registry writes each name the way its owner does; the row is normalised here, at generation,
    // rather than by editing another workflow's seed.
    for (const board of boards.shown) expect(board.short).toBe(chipLabel(board.short));
    expect(boards.shown.map((b) => b.short)).toContain('Australian curriculum');
  });

  it('reports a registry total larger than the handful it shows', () => {
    // The exact numbers are regenerated by the build (the content pipeline rebuilds the registry
    // on its own schedule), so what is asserted here is the relationship, not a frozen count.
    expect(boards.total).toBeGreaterThan(boards.shown.length);
    expect(boards.countries).toBeGreaterThan(10);
  });

  it('says where it came from', () => {
    expect(boards.source).toBe('content/curriculum/frameworks.seed.json');
  });

  it('is what the build script produces from the registry as it stands today', () => {
    const rebuilt = buildLandingBoards(seed, CURATED);
    // Ids, chip labels and long names must already match; only the registry's own counts may have
    // moved since the last build, and `bun run build` regenerates those before anything ships.
    expect(rebuilt.shown).toEqual(boards.shown);
  });
});

describe('chipLabel', () => {
  it('lowers a trailing common noun and nothing else', () => {
    expect(chipLabel('Australian Curriculum')).toBe('Australian curriculum');
    expect(chipLabel('Ontario Board')).toBe('Ontario board');
  });

  it('leaves proper nouns, acronyms and already-correct names exactly as written', () => {
    for (const name of ['CBSE', 'IB', 'Edexcel IGCSE', 'Telangana SSC', 'UK national curriculum']) {
      expect(chipLabel(name)).toBe(name);
    }
  });

  it('never lowers a name’s first word — that word is the board', () => {
    expect(chipLabel('Curriculum for Wales')).toBe('Curriculum for Wales');
    expect(chipLabel('National curriculum')).toBe('National curriculum');
  });

  it('is idempotent, so a second build cannot drift', () => {
    for (const board of CURATED)
      expect(chipLabel(chipLabel(board.short))).toBe(chipLabel(board.short));
  });
});

describe('countLine', () => {
  it('fills every placeholder from the data', () => {
    const line = countLine('{shown} of {total} across {countries}', {
      shown: 18,
      total: 249,
      countries: 65,
    });
    expect(line).toBe('18 of 249 across 65');
  });

  it('leaves no unfilled placeholder on the page', () => {
    const line = countLine(
      'Shown here: {shown} of the {total} frameworks in our registry, across {countries} countries.',
      { shown: boards.shown.length, total: boards.total, countries: boards.countries },
    );
    expect(line).not.toContain('{');
  });
});
