"""Emit the card-spec JSON Schema from the Pydantic source of truth (``specs.py``).

Run: ``uv run python -m classess_gateway.plexus.codegen``

Writes ``packages/contracts/schemas/plexus.schema.json`` — the language-neutral artifact the
bun wiring turns into ``packages/contracts/src/generated/plexus.ts``. The output is checked in;
CI (``test_plexus_codegen.py`` here, ``plexus.codegen.test.ts`` in the contracts package)
regenerates and fails on any drift, so the contract can never silently diverge from the models.

``--check`` regenerates in memory and exits non-zero on drift without writing (CI convenience).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from pydantic.json_schema import models_json_schema

from classess_gateway.plexus.specs import EXPORTED

_HEADER = "generated by classess_gateway.plexus.codegen from specs.py — do not edit by hand"

_SCHEMA_PATH = (
    Path(__file__).resolve().parents[5]
    / "packages"
    / "contracts"
    / "schemas"
    / "plexus.schema.json"
)


def build_schema() -> dict:
    """The combined JSON Schema: every exported model under ``$defs`` with ``$ref`` links."""
    _, defs = models_json_schema(
        [(m, "serialization") for m in EXPORTED],
        by_alias=True,
        ref_template="#/$defs/{model}",
    )
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": _HEADER,
        "$defs": defs["$defs"],
    }


def render() -> str:
    """Deterministic JSON text (stable field order + trailing newline) for byte-exact diffs."""
    return json.dumps(build_schema(), indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        current = _SCHEMA_PATH.read_text(encoding="utf-8") if _SCHEMA_PATH.exists() else ""
        if current != text:
            print(f"DRIFT: {_SCHEMA_PATH} is stale — rerun the codegen module")
            return 1
        print(f"ok: {_SCHEMA_PATH} matches specs.py")
        return 0
    _SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    _SCHEMA_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {_SCHEMA_PATH} ({len(EXPORTED)} models)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
