"""The twelve golden boards, checked from the brain's side.

`test_board_pipelines.py` asks whether a prompt reaches the right pipeline. This file asks the
harder question about the same twelve boards: **is what she would actually draw true?**

The fixtures in ``apps/web-pwa/src/wobo/goldens/*.json`` are one recorded turn each, generated by
``apps/web-pwa/src/wobo/goldens/build.ts``. The hand plays those exact bytes in the bench and reads
the DOM back (``apps/web-pwa/tests/board.spec.ts``); here the same bytes go through the brain:

*   every object is validated against the grammar the brain enforces (BOARD.md §2, §3) — including
    the law that nothing is placed by pixels and the law that a visible numeral names its check;
*   **every number on every board is recomputed here, independently**, from the physics or the
    arithmetic, and has to match what the fixture draws (BOARD.md §6). The recomputations live in
    :data:`RECOMPUTE` and are deliberately written a different way round from the generator, so a
    mistake would have to be made twice, in two languages, to survive;
*   the stream obeys §4: ids are unique, a reference points backwards, the first ink beats the first
    sentence, ``done`` closes the turn, and the plan stays inside the §10 budget;
*   the expectation block the hand asserts against is derived from the same plan, so the two halves
    of the contract cannot drift apart while both keep passing.
"""

from __future__ import annotations

import json
import math
import re
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest
from classess_gateway import board_schema as mirror
from classess_gateway.board import schema, verify

REPO = Path(__file__).resolve().parents[3]
GOLDENS = REPO / "apps" / "web-pwa" / "src" / "wobo" / "goldens"

#: Standard gravity as the boards use it.
G = 9.81

# --- loading -------------------------------------------------------------------------------


def _load(name: str) -> dict[str, Any]:
    return json.loads((GOLDENS / f"{name}.json").read_text())


MANIFEST: list[dict[str, Any]] = json.loads((GOLDENS / "manifest.json").read_text())
NAMES: list[str] = [entry["name"] for entry in MANIFEST]
BOARDS: dict[str, dict[str, Any]] = {name: _load(name) for name in NAMES}


def objects_of(board: dict[str, Any]) -> list[dict[str, Any]]:
    return [event["object"] for event in board["plan"] if event["type"] == "ink"]


def numbers_of(board: dict[str, Any]) -> list[dict[str, Any]]:
    return [obj for obj in objects_of(board) if obj["kind"] == "number"]


# --- the independent recomputation of every drawn quantity ---------------------------------
#
# One entry per number object on every board. A number with no entry here fails the suite: a
# quantity nobody can recompute has no business being drawn.

_SIN30 = math.sin(math.radians(30))
_COS30 = math.cos(math.radians(30))
_SIN45 = math.sin(math.radians(45))
_COS45 = math.cos(math.radians(45))


def _titration_ph(added_ml: float) -> float:
    """A strong acid with a strong base: 25.00 mL of 0.1000 M, titrated with 0.1000 M."""
    acid = 25.0 * 0.1
    base = added_ml * 0.1
    total = 25.0 + added_ml
    if math.isclose(acid, base):
        return 7.0
    if base < acid:
        return -math.log10((acid - base) / total)
    return 14 + math.log10((base - acid) / total)


RECOMPUTE: dict[tuple[str, str], Callable[[], float]] = {
    # maths — arithmetic done the long way round
    ("pythagoras", "a-squared"): lambda: 4**2,
    ("pythagoras", "b-squared"): lambda: 3**2,
    ("pythagoras", "c-squared"): lambda: 5**2,
    ("tangent-parabola", "slope-value"): lambda: verify.value_at(
        verify.derivative("x**2", "x"), "x", 1.5
    ),
    ("tangent-parabola", "point-value"): lambda: verify.value_at("x**2", "x", 1.5),
    ("long-division", "quotient"): lambda: 4823 // 7,
    ("long-division", "remainder"): lambda: 4823 % 7,
    # physics — from the kinematics and the free body, not from the generator's own algebra
    ("projectile-apex", "apex-height"): lambda: (20 * _SIN45) ** 2 / (2 * G),
    ("projectile-apex", "apex-speed"): lambda: 20 * _COS45,
    ("projectile-apex", "apex-vertical"): lambda: 20 * _SIN45 - G * (20 * _SIN45 / G),
    ("projectile-apex", "apex-time"): lambda: 20 * _SIN45 / G,
    ("free-body-incline", "weight-value"): lambda: 5 * G,
    ("free-body-incline", "along-value"): lambda: 5 * G * _SIN30,
    ("free-body-incline", "normal-value"): lambda: 5 * G * _COS30,
    ("free-body-incline", "accel-value"): lambda: G * _SIN30,
    ("series-circuit", "emf"): lambda: 12,
    ("series-circuit", "resistor-1-value"): lambda: 4,
    ("series-circuit", "resistor-2-value"): lambda: 6,
    ("series-circuit", "resistor-3-value"): lambda: 2,
    ("series-circuit", "total-resistance"): lambda: 4 + 6 + 2,
    ("series-circuit", "current"): lambda: 12 / (4 + 6 + 2),
    ("series-circuit", "drop-1"): lambda: 12 / 12 * 4,
    ("series-circuit", "drop-2"): lambda: 12 / 12 * 6,
    ("series-circuit", "drop-3"): lambda: 12 / 12 * 2,
    # chemistry — the coefficients are SOLVED by the brain's own balancer
    ("photosynthesis-balance", "coefficient-1"): lambda: _balanced()[0],
    ("photosynthesis-balance", "coefficient-2"): lambda: _balanced()[1],
    ("photosynthesis-balance", "coefficient-3"): lambda: _balanced()[2],
    ("photosynthesis-balance", "coefficient-4"): lambda: _balanced()[3],
    ("titration-curve", "start-ph"): lambda: _titration_ph(0),
    ("titration-curve", "equivalence-volume"): lambda: 25.0 * 0.1 / 0.1,
    ("titration-curve", "equivalence-ph"): lambda: _titration_ph(25),
    ("titration-curve", "end-ph"): lambda: _titration_ph(50),
    # social — a span is a subtraction, and it is still computed
    ("timeline", "span"): lambda: 1947 - 1857,
}

_BALANCED: list[int] | None = None


def _balanced() -> list[int]:
    """6 CO2 + 6 H2O -> C6H12O6 + 6 O2, solved once by the verifier and cached for the run."""
    global _BALANCED
    if _BALANCED is None:
        _BALANCED = verify.balance(["CO2", "H2O"], ["C6H12O6", "O2"])
    return _BALANCED


# --- the shape of the set ------------------------------------------------------------------


def test_there_are_twelve_boards_across_the_domains() -> None:
    assert len(MANIFEST) == 12
    subjects = [entry["subject"] for entry in MANIFEST]
    assert subjects.count("math") == 3
    assert subjects.count("physics") == 3
    assert subjects.count("chemistry") == 3
    assert subjects.count("biology") + subjects.count("social") == 3
    # Every board names a learner's prompt; a golden with no question behind it is a demo.
    for entry in MANIFEST:
        assert entry["prompt"].strip()
        assert entry["presentation"] in mirror.PRESENTATIONS


@pytest.mark.parametrize("name", NAMES)
def test_the_manifest_and_the_fixture_agree(name: str) -> None:
    entry = next(e for e in MANIFEST if e["name"] == name)
    board = BOARDS[name]
    assert entry["objects"] == len(objects_of(board))
    assert entry["numbers"] == len(numbers_of(board))
    assert entry["prompt"] == board["prompt"]


# --- the grammar ---------------------------------------------------------------------------


@pytest.mark.parametrize("name", NAMES)
def test_every_object_is_one_the_brain_would_let_through(name: str) -> None:
    """Both validators: the hand-maintained table and the mirror generated from the TS grammar."""
    for obj in objects_of(BOARDS[name]):
        assert schema.validate_object(obj) == [], f"{name}/{obj['id']}"
        assert mirror.is_valid_object(obj), f"{name}/{obj['id']} failed the generated mirror"


@pytest.mark.parametrize("name", NAMES)
def test_nothing_is_placed_by_pixels(name: str) -> None:
    board = BOARDS[name]
    forms = {"target", "object", "focus", "board"}
    for obj in objects_of(board):
        anchor = obj.get("anchor")
        assert isinstance(anchor, dict), f"{name}/{obj['id']} has no anchor"
        assert len(forms & set(anchor)) == 1, f"{name}/{obj['id']} names no single anchor form"
        assert schema.validate_anchor(anchor) == []


@pytest.mark.parametrize("name", NAMES)
def test_a_reference_always_points_backwards(name: str) -> None:
    """"This one" has to mean something already on the board (BOARD.md §4)."""
    drawn: set[str] = set()
    for obj in objects_of(BOARDS[name]):
        for field in (obj.get("anchor"), obj.get("from"), obj.get("to")):
            if isinstance(field, dict) and "object" in field:
                assert field["object"] in drawn, f"{name}/{obj['id']} -> {field['object']}"
        if obj["kind"] == "erase":
            assert obj["object"] in drawn
        assert obj["id"] not in drawn, f"{name}/{obj['id']} is drawn twice"
        drawn.add(obj["id"])


# --- the streaming protocol and the budgets ------------------------------------------------


@pytest.mark.parametrize("name", NAMES)
def test_the_turn_is_a_well_formed_stream(name: str) -> None:
    plan = BOARDS[name]["plan"]
    assert plan, name
    assert plan[-1]["type"] == "done", f"{name} never closes the turn"
    assert [e["type"] for e in plan].count("done") == 1
    times = [event.get("t", 0) for event in plan]
    assert times == sorted(times), f"{name} streams out of order"
    for event in plan:
        assert mirror.parse_board_event(event) is not None, f"{name}: {event['type']} is malformed"


@pytest.mark.parametrize("name", NAMES)
def test_the_pen_starts_before_the_first_sentence_ends(name: str) -> None:
    """BOARD.md §4: the first ink event must arrive before the first sentence finishes."""
    plan = BOARDS[name]["plan"]
    first_say = next(e for e in plan if e["type"] == "say")
    first_ink = next(e for e in plan if e["type"] == "ink")
    # 165 words a minute (the brain's own WORDS_PER_MINUTE), so a sentence lasts this long.
    words = len(first_say["text"].split())
    sentence_ms = words / 165 * 60_000
    assert first_ink.get("t", 0) <= first_say.get("t", 0) + sentence_ms, name


@pytest.mark.parametrize("name", NAMES)
def test_the_plan_stays_inside_the_budget(name: str) -> None:
    """BOARD.md §10: forty objects typical, two hundred the ceiling."""
    count = len(objects_of(BOARDS[name]))
    assert 0 < count <= 200, f"{name} draws {count} objects"


# --- the law that matters most: every number is computed and verified -----------------------

CHECK_NAME = re.compile(r"^board\.([a-z_]+):.+$")
# The verifiers that may sign a mark. Each one is a real function in `board.verify`.
CHECKERS = {
    "readable",
    "expressions_agree",
    "numbers_agree",
    "in_bounds",
    "units_agree",
    "equation_balances",
    "fact_supported",
}


@pytest.mark.parametrize("name", NAMES)
def test_every_visible_numeral_names_a_real_verifier(name: str) -> None:
    for obj in objects_of(BOARDS[name]):
        fields = ("text", "tex", "label", "title", "value")
        visible = " ".join(str(obj.get(k) or "") for k in fields)
        if not schema.contains_number(visible):
            continue
        check = str(obj.get("check") or "")
        match = CHECK_NAME.match(check)
        assert match, f"{name}/{obj['id']} shows a number under a check named {check!r}"
        checker = match.group(1)
        assert checker in CHECKERS, f"{name}/{obj['id']} names an unknown checker {checker!r}"
        assert callable(getattr(verify, checker)), checker


@pytest.mark.parametrize("name", NAMES)
def test_no_number_is_drawn_unverified(name: str) -> None:
    for obj in numbers_of(BOARDS[name]):
        assert obj.get("verified") is True, f"{name}/{obj['id']}"
        assert not mirror.is_drawable({**obj, "verified": False}), (
            "the mirror must refuse an unverified number"
        )


@pytest.mark.parametrize("name", NAMES)
def test_every_number_on_the_board_is_recomputed_here_and_agrees(name: str) -> None:
    """The heart of it: nothing is drawn that this file cannot work out for itself."""
    for obj in numbers_of(BOARDS[name]):
        key = (name, obj["id"])
        assert key in RECOMPUTE, f"{name}/{obj['id']} is a number nobody recomputes"
        expected = float(RECOMPUTE[key]())
        drawn = float(obj["value"])
        result = verify.numbers_agree(f"{name}/{obj['id']}", drawn, expected)
        assert result.passed, result.detail


def test_the_recomputation_table_covers_the_boards_and_nothing_else() -> None:
    """A stale entry is as bad as a missing one: it would hide a number that quietly vanished."""
    drawn = {(name, obj["id"]) for name in NAMES for obj in numbers_of(BOARDS[name])}
    assert set(RECOMPUTE) == drawn


def test_a_number_drawn_at_the_wrong_precision_would_be_caught() -> None:
    """The suite has to be able to fail. A nudged apex height must not survive the cross-check."""
    truth = (20 * _SIN45) ** 2 / (2 * G)
    assert verify.numbers_agree("apex height", truth * 1.001, truth).passed is False


# --- the two halves of the contract stay in step -------------------------------------------


@pytest.mark.parametrize("name", NAMES)
def test_the_expectation_block_still_describes_the_plan(name: str) -> None:
    """The hand asserts against `expect`; the brain asserts against the plan. They are one thing."""
    board = BOARDS[name]
    objects = objects_of(board)
    expect = board["expect"]
    assert expect["ids"] == [obj["id"] for obj in objects]
    assert expect["kinds"] == [obj["kind"] for obj in objects]
    forms = []
    for obj in objects:
        anchor = obj["anchor"]
        forms.append(next(f for f in ("board", "object", "target", "focus") if f in anchor))
    assert expect["anchors"] == forms
    hangs = [
        [obj["id"], obj["anchor"]["object"]] for obj in objects if "object" in obj["anchor"]
    ]
    assert [list(pair) for pair in expect["hangsOff"]] == hangs
    assert [n["id"] for n in expect["numbers"]] == [obj["id"] for obj in numbers_of(board)]


# --- the domain checks the pipelines would have run ----------------------------------------


def test_photosynthesis_balances_by_the_brains_own_balancer() -> None:
    coefficients = _balanced()
    assert coefficients == [6, 6, 1, 6]
    drawn = [obj["value"] for obj in numbers_of(BOARDS["photosynthesis-balance"])]
    assert drawn == coefficients
    # And the tally she writes on the board is the tally the coefficients produce.
    table = next(o for o in objects_of(BOARDS["photosynthesis-balance"]) if o["kind"] == "table")
    assert table["rows"][1:] == [["C", "6", "6"], ["H", "12", "12"], ["O", "18", "18"]]


def test_the_tangent_board_agrees_with_the_cas() -> None:
    assert verify.expressions_agree(verify.derivative("x**2", "x"), "2*x").passed
    slope = next(o for o in numbers_of(BOARDS["tangent-parabola"]) if o["id"] == "slope-value")
    assert verify.numbers_agree("slope", slope["value"], verify.value_at("2*x", "x", 1.5)).passed


def test_the_projectile_apex_agrees_from_two_directions() -> None:
    """Kinematics and energy conservation are different routes to one height; both must land."""
    board = BOARDS["projectile-apex"]
    height = next(o for o in numbers_of(board) if o["id"] == "apex-height")
    v_up = 20 * _SIN45
    kinematic = v_up**2 / (2 * G)
    # ½mv² = mgh, mass cancels — a second route to the same number.
    energy = 0.5 * v_up**2 / G
    assert verify.numbers_agree("apex height", kinematic, energy).passed
    assert verify.numbers_agree("apex height", height["value"], energy).passed
    assert verify.in_bounds("apex height", height["value"], 0, 25).passed


def test_the_series_circuit_obeys_kirchhoff() -> None:
    numbers = {obj["id"]: obj["value"] for obj in numbers_of(BOARDS["series-circuit"])}
    drops = [numbers["drop-1"], numbers["drop-2"], numbers["drop-3"]]
    # The drops around a loop add up to the source. If they did not, the board would be a lie.
    assert verify.numbers_agree("loop", sum(drops), numbers["emf"]).passed
    assert verify.numbers_agree(
        "series", numbers["total-resistance"],
        numbers["resistor-1-value"] + numbers["resistor-2-value"] + numbers["resistor-3-value"],
    ).passed


def test_the_timeline_marks_sit_where_their_years_are() -> None:
    """Nothing on a timeline is eyeballed: every mark's x is its year, mapped."""
    board = BOARDS["timeline"]
    axis = next(o for o in objects_of(board) if o["kind"] == "axis")
    left = axis["anchor"]["board"][0]
    span = axis["max"] - axis["min"]
    for obj in objects_of(board):
        if not obj["id"].startswith("mark-"):
            continue
        year = int(obj["id"].split("-")[1])
        expected = left + (year - axis["min"]) / span * axis["length"]
        assert math.isclose(obj["anchor"]["board"][0], expected, abs_tol=1e-6), obj["id"]


def test_the_benzene_ring_is_a_regular_hexagon_named_carbon_to_carbon() -> None:
    board = BOARDS["benzene"]
    atoms = [o for o in objects_of(board) if o["kind"] == "atom"]
    bonds = [o for o in objects_of(board) if o["id"].startswith("bond-")]
    assert len(atoms) == 6 and len(bonds) == 6
    assert all(a["symbol"] == "C" for a in atoms)
    # Every bond names the two carbons it joins; not one of them is a coordinate.
    joins = [(b["anchor"]["object"], b["to"]["object"]) for b in bonds]
    assert joins == [
        ("c1", "c2"), ("c2", "c3"), ("c3", "c4"), ("c4", "c5"), ("c5", "c6"), ("c6", "c1")
    ]
    # The carbons themselves sit on a regular hexagon: six equal sides, one centre.
    ring = [tuple(a["anchor"]["board"]) for a in atoms]
    sides = [math.dist(ring[i], ring[(i + 1) % 6]) for i in range(6)]
    assert max(sides) - min(sides) < 1e-6
    centre = (sum(p[0] for p in ring) / 6, sum(p[1] for p in ring) / 6)
    radii = [math.dist(p, centre) for p in ring]
    assert max(radii) - min(radii) < 1e-6
